DROP TABLE IF EXISTS PRICE;


CREATE TABLE PRICES (
  PRICE_LIST INT AUTO_INCREMENT PRIMARY KEY,
  BRAND_ID INT NOT NULL,
  START_DATE DATETIME NOT NULL,
  END_DATE DATETIME NOT NULL,
  PRODUCT_ID INT NOT NULL,
  PRIORITY INT DEFAULT 0,
  PRICE DECIMAL(10,2) DEFAULT 0,
  CURR VARCHAR(250) DEFAULT NULL
);